### PR TITLE
Add option to skip static index middleware

### PR DESCRIPTION
**Pull request by ersherr**
Hello! Super useful library!

I get the error below when I serve non-Vite JSON response content from my Express app, unless I disable injecting the viteIndexMiddleware (which fixes the issue).

```
ERROR  - error unhandledRejection: Cannot set headers after they are sent to the client         22:26:57

  at new NodeError (node:internal/errors:387:5)
  at ServerResponse.setHeader (node:_http_outgoing:644:11)
  at ServerResponse.header (node_modules/express/lib/response.js:771:10)
  at ServerResponse.contentType (node_modules/express/lib/response.js:599:15)
  at ServerResponse.send (node_modules/express/lib/response.js:145:14)
  at node_modules/vite-express/dist/main.js:105:21
  at Generator.next (<anonymous>)
  at fulfilled (node_modules/vite-express/dist/main.js:26:58)
```

### CODE REVIEW

**Comment by ersherr** [comment]
Actually -- I think rather than passing a boolean, we need to pass a regex that describes on which paths it should run these lines:
```
      const html = await server.transformIndexHtml(req.originalUrl, template);
      res.send(getTransformedHTML(html, req));
```
That way if you are only serving your Vite content over a subpath, and have other routes on the other paths, you can tell it not to run these lines (and therefore prevent it from causing the error message above).

**Comment by szymmis** [comment]
Hi @ersherr sorry for late response. Can you describe me your problem in more details? I'm sure that we cannot proceed with your solution because disabling static index middleware doesn't make sense - it is a piece of code that serves what Vite spits out. Disabling it would mean that you have just express without Vite. 
Could you show me some code to take a look at? More precisely, where you register your path that serves the JSON in relation to starting/binding vite-express.

**Comment by ersherr** [comment]
Yes, for sure!

What I am aiming to do is, and definitely open to any thoughts + guidance on the best way to achieve (potential approach in this recently updated PR), is to have the Vite / Express dev server ignore certain paths. The reason is that, in current state in my local dev environment, it seems to try and set headers after the request has been sent (for vanilla Express API requests, with their paths configured using the `routing-controllers` library). 

I know that in theory it shouldn't match these requests at all in the first place, because I register ViteExpress at the end of my Express index.ts like so:

```
const server = app.listen(3000, async () => {
    if (EnvUtils.isDev)
      console.log(
        chalk`{green ✓ You're in development mode!}`
      );
    console.log("  Press CTRL-C to stop\n");
};

ViteExpress.bind(app, server, () => console.log("ViteExpress bound to server"));
```

But, it seems that in my local env it does match these requests, and I end up getting the `unhandledRejection: Cannot set headers after they are sent to the client`, as a result unless I specify that it should ignore the API paths (which in my case are `/api/v1/*`).

Also happy to connect in any format that works if helpful!

**Comment by szymmis** [comment]
Okay, I guess that you are talking about [this package](https://www.npmjs.com/package/routing-controllers)? It seems like a pretty solid package that does a lot of things so I'm not surprised that it might not work with `vite-express` out of the box.

First of all, thanks a lot for taking your time to describe the problem and open this PR. I really appreciate that!

When it comes to your change, I like it. That's something that I thought about some time ago - to have a way to pass a RegEx or something that will describe that certain paths are matched or not, so that's definitely a good path. What I thought tho, is it would be nice to be able to specify also a function apart from simple regex, that way you could have any logic you want to describe if certain path should be matched by `vite-express` and send HTML or not.

Because of that I'm trying to think about better name for the variable, so that it will describe idea that it can be also a function, but also shorter I think. Maybe something like `ignorePaths`. Tell me what do you think about that - the name and the idea to pass also a function - I'm really interested in what you think about that!

It would be wonderful if you would like to make that change in your PR. If you want to, then I want to point out one think that in current code doesn't work.

```js
if (viteExcludePattern && req.path.match(viteExcludePattern)) return;
```

This will cause the server to hang when you access the site that will be matched by that regex. We need to return with call to `next()` function that passes the invocation to the next function in express chain, so basically when you call `next()` you make it possible for your next handlers to act.

```js
if (viteExcludePattern && req.path.match(viteExcludePattern)) return next();
```

That's a lot of text :sweat_smile:. Let me know what you think about that!

**Comment by szymmis** [comment]
Closing this PR as #83 will implement this feature.

**Pull request closed without merging**
